# Libraries

In [1]:
import pandas as pd                 # pandas is a dataframe library
import numpy as np                  # numpy is a mathematical library
import matplotlib.pyplot as plt     # matplotlib.pyplot draw grphs
import seaborn as sns               # seaborn is a statistical data visualization library

# Exploring pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('titanic.csv')
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [4]:
df = df.drop(columns=['PassengerId','Name','Ticket','Embarked', 'Cabin', 'Fare'])

In [5]:
df.head(10)

Survived  Pclass     Sex   Age  SibSp  Parch
0         0       3    male  22.0      1      0
1         1       1  female  38.0      1      0
2         1       3  female  26.0      0      0
3         1       1  female  35.0      1      0
4         0       3    male  35.0      0      0
5         0       3    male   NaN      0      0
6         0       1    male  54.0      0      0
7         0       3    male   2.0      3      1
8         1       3  female  27.0      0      2
9         1       2  female  14.0      1      0

In [6]:
df.describe()

Survived      Pclass         Age       SibSp       Parch
count  891.000000  891.000000  714.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594
std      0.486592    0.836071   14.526497    1.102743    0.806057
min      0.000000    1.000000    0.420000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000
50%      0.000000    3.000000   28.000000    0.000000    0.000000
75%      1.000000    3.000000   38.000000    1.000000    0.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000

# Missing values

In [7]:
"""
1) For numerical data, Replace nan values with calss average, or remove rows
2) For categorical data, replace nan values with most frequent value or remove rows
"""

'\n1) For numerical data, Replace nan values with calss average, or remove rows\n2) For categorical data, replace nan values with most frequent value or remove rows\n'

In [8]:
df = df.dropna()

In [9]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
dtype: int64

In [10]:
df

Survived  Pclass     Sex   Age  SibSp  Parch
0           0       3    male  22.0      1      0
1           1       1  female  38.0      1      0
2           1       3  female  26.0      0      0
3           1       1  female  35.0      1      0
4           0       3    male  35.0      0      0
..        ...     ...     ...   ...    ...    ...
885         0       3  female  39.0      0      5
886         0       2    male  27.0      0      0
887         1       1  female  19.0      0      0
889         1       1    male  26.0      0      0
890         0       3    male  32.0      0      0

[714 rows x 6 columns]

# Manage DataTypes

In [11]:
df.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
dtype: object

In [12]:
df = df.astype({'Age': 'int'})

# Categorical to numerical data

In [13]:
# Ordinal Normalization / Label Encoding / Ordinal encoding
mapping = {cat : i for i,cat in enumerate(df['Sex'].unique())}
mapping

{'male': 0, 'female': 1}

# Applying lambda function to a dataframe

In [14]:
df["Sex"] = df['Sex'].apply(lambda x: mapping[x])
df.head(10)

Survived  Pclass  Sex  Age  SibSp  Parch
0          0       3    0   22      1      0
1          1       1    1   38      1      0
2          1       3    1   26      0      0
3          1       1    1   35      1      0
4          0       3    0   35      0      0
6          0       1    0   54      0      0
7          0       3    0    2      3      1
8          1       3    1   27      0      2
9          1       2    1   14      1      0
10         1       3    1    4      1      1

# Normalizaion

In [15]:
df.head()

Survived  Pclass  Sex  Age  SibSp  Parch
0         0       3    0   22      1      0
1         1       1    1   38      1      0
2         1       3    1   26      0      0
3         1       1    1   35      1      0
4         0       3    0   35      0      0

In [16]:
standardization_columns = []
zero_one_normaization_columns = ['Age']

# Standardization / Standard Scaling / z-score normalization
for col in standardization_columns:
    mean = df[col].mean()
    std = df[col].std()
    df[col] = (df[col] - mean) / std

# Min Max Scaling / 0-1 normalization
for col in zero_one_normaization_columns:
    max = df[col].max()
    min = df[col].min()
    df[col] = (df[col] - min) / (max - min)

df.head(10)

Survived  Pclass  Sex     Age  SibSp  Parch
0          0       3    0  0.2750      1      0
1          1       1    1  0.4750      1      0
2          1       3    1  0.3250      0      0
3          1       1    1  0.4375      1      0
4          0       3    0  0.4375      0      0
6          0       1    0  0.6750      0      0
7          0       3    0  0.0250      3      1
8          1       3    1  0.3375      0      2
9          1       2    1  0.1750      1      0
10         1       3    1  0.0500      1      1

In [17]:
df.describe()

Survived      Pclass         Sex         Age       SibSp       Parch
count  714.000000  714.000000  714.000000  714.000000  714.000000  714.000000
mean     0.406162    2.236695    0.365546    0.370991    0.512605    0.431373
std      0.491460    0.838250    0.481921    0.181706    0.929783    0.853289
min      0.000000    1.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    1.000000    0.000000    0.250000    0.000000    0.000000
50%      0.000000    2.000000    0.000000    0.350000    0.000000    0.000000
75%      1.000000    3.000000    1.000000    0.475000    1.000000    1.000000
max      1.000000    3.000000    1.000000    1.000000    5.000000    6.000000

In [18]:
df

Survived  Pclass  Sex     Age  SibSp  Parch
0           0       3    0  0.2750      1      0
1           1       1    1  0.4750      1      0
2           1       3    1  0.3250      0      0
3           1       1    1  0.4375      1      0
4           0       3    0  0.4375      0      0
..        ...     ...  ...     ...    ...    ...
885         0       3    1  0.4875      0      5
886         0       2    0  0.3375      0      0
887         1       1    1  0.2375      0      0
889         1       1    0  0.3250      0      0
890         0       3    0  0.4000      0      0

[714 rows x 6 columns]

# Machine Learning using Linear regression

## Prediction

In [19]:
'''
While writing a program, we need a few extra things:
1) What do we use as the starting values for w and b?
2) When do we stop learning?
2.5) How do we evaluate a model and how can we best tell that our model is good or not?
3) Do we do one value at a time? Batch of values at a time? All values at a time?
4) how do we save the model so we don't have to train it every time we run our file?
5) How do we use a saved model to make predictions?
'''

"\nWhile writing a program, we need a few extra things:\n1) What do we use as the starting values for w and b?\n2) When do we stop learning?\n2.5) How do we evaluate a model and how can we best tell that our model is good or not?\n3) Do we do one value at a time? Batch of values at a time? All values at a time?\n4) how do we save the model so we don't have to train it every time we run our file?\n5) How do we use a saved model to make predictions?\n"

In [43]:
def forward_all(X, w):
    return np.exp(np.matmul(X, w.transpose()))

def sigmoid(X):
    return 1/(1+np.exp(-X))

In [44]:
def gradients(X, y, y_pred):
    d = X * (y_pred - y)
    d_avg = np.mean(d, axis=0)
    return d_avg

In [45]:
bias_column = [1 for i in range(len(df))]

In [46]:
df2 = df.copy()
df2['bias_feature'] = bias_column

In [47]:
df2

Survived  Pclass  Sex     Age  SibSp  Parch  bias_feature
0           0       3    0  0.2750      1      0             1
1           1       1    1  0.4750      1      0             1
2           1       3    1  0.3250      0      0             1
3           1       1    1  0.4375      1      0             1
4           0       3    0  0.4375      0      0             1
..        ...     ...  ...     ...    ...    ...           ...
885         0       3    1  0.4875      0      5             1
886         0       2    0  0.3375      0      0             1
887         1       1    1  0.2375      0      0             1
889         1       1    0  0.3250      0      0             1
890         0       3    0  0.4000      0      0             1

[714 rows x 7 columns]

In [48]:
X = df2.drop(columns=['Survived']).values
y = df2['Survived'].values.reshape(-1,1)

In [49]:
X.shape, y.shape

((714, 6), (714, 1))

In [50]:
w = np.random.randn(1, X.shape[1])
lr = 0.1

Parameters: Values that the model learns: weights and biases
Hypereparametes: Value the effect the results, but the model doesn't learn them: learning rate, number of epoc

In [ ]:
epoch = 10000

for i in range(epoch):
    y_out = forward_all(X, w)

    y_pred = sigmoid(y_out)

    print("Loss: ", np.mean((y_pred - y)**2))

    w = w - lr * gradients(X, y, y_pred)

In [53]:
y_pred = forward_all(X, w)

In [54]:
y_pred_binary = []
for x in y_pred:
    if x > 0.5:
        y_pred_binary.append(1)
    else:
        y_pred_binary.append(0)

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
accuracy_score(y, y_pred_binary)

0.5938375350140056

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

X = PolynomialFeatures(degree=2).fit_transform(X)

model = LinearRegression()

model.fit(X,y)

In [ ]:
model.score(X,y)

# Classification Model using Logistic Regression

In [57]:
class LinearLayer:
    def __init__(self, input_size, output_size, lr):
        self.input_size = input_size
        self.output_size = output_size

        self.w = np.random.randn(output_size, input_size)
        self.b = np.random.randn(output_size, 1)

        self.lr = lr

    def forward(self, X):
        self.input = X
        self.output = np.matmul(self.w, X.transpose()) + self.b
        return self.output

    def backward(self, error):
        self.w_grad = np.matmul(error, self.input)
        self.b_grad = np.mean(error, axis=1).reshape(-1,1)
        self.error = np.matmul(self.w.transpose(), error)

        self.w = self.w - self.lr * self.w_grad
        self.b = self.b - self.lr * self.b_grad

        return self.error
    
class SigmoidLayer:
    def __init__(self):
        pass

    def forward(self, X):
        self.input = X
        self.output = 1/(1+np.exp(-X))
        return self.output

    def backward(self, error):
        self.error = error * self.output * (1-self.output)
        return self.error
    
class MSE: 
    def __init__(self):
        pass

    def forward(self, y_pred, y):
        self.input = y_pred
        self.output = np.mean((y_pred - y)**2)
        return self.output

    def backward(self, y_pred, y):
        self.error = 2*(y_pred - y)/len(y)
        return self.error

In [ ]:
class Model:
    def __init__(self, n_layers = 1, input_dim = 4, output_dim = 1, n_neurons = [2]):
        n_neurons = [input_dim] + n_neurons + [output_dim]
        self.layers = []
        for idx, n in enumerate(range(n_layers)):
            self.layers.append(LinearLayer(n_neurons[idx], n_neurons[idx+1]))
            self.layers.append(SigmoidLayer())

        self.layers.append(MSE())

    def forward(self, X, y):

        self.X = X
        self.y = y

        for layer in self.layers[:-1]:
            X = layer.forward(X)

        self.y_pred = X

        self.loss = self.layers[-1].forward(y_pred, y)
        
        return self.y_pred
        

    def backward(self):
        error = self.layers[-1].backward(self.y_pred, self.y)
        for layer in self.layers.reverse()[1:]:
            error = layer.backward(error)



# why not numpy anymore

# PyTorch and TensorFlow

In [72]:
a = np.array(10)
b = np.array(20)

c = a + b
c

30

In [61]:
import torch

In [73]:
a = torch.Tensor([10])
b = torch.Tensor([20])

c = a + b
c

tensor([30.])

In [74]:
a = torch.tensor([10.], requires_grad=True)
b = torch.tensor([20.], requires_grad=True)

c = a + b
c

tensor([30.], grad_fn=<AddBackward0>)

In [75]:
c.backward()

In [76]:
a, b

(tensor([10.], requires_grad=True), tensor([20.], requires_grad=True))

In [77]:
a.grad, b.grad

(tensor([1.]), tensor([1.]))

In [78]:
a = a - 0.1 * a.grad
b = b - 0.1 * b.grad

a, b

(tensor([9.9000], grad_fn=<SubBackward0>),
 tensor([19.9000], grad_fn=<SubBackward0>))